import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import EventTable from "../components/EventTable";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <EventTable />
      </main>
    </div>
  );
}

/* 
TODO:
  - Landing Page 
    - Main Nav Bar
    - "Buy Ticket Button"
    - Use Vector Images on Hero Section
    - Add Images to Hero Section
    - Scrollable Event Schedule Section
    - Set Background Color
    - Set Google Font: Inter

  - Event Page
    - Title + Subtitle
    - Draggable Tab
      - Organizer
      - Speakers [Card - Image + Name + Company Name + Description]
      - Location
      - Schedule
      - Sponsors
*/
